### Mostrar la informacion de la api
GET http://localhost:1904/api 

### Mostrar todos los usuarios
GET http://localhost:1904/api/users

### Registrar un usuario
POST http://localhost:1904/api/users/register
Content-Type: application/json

{
  "username": "Tatiana Vega",
  "password": "1909",
  "email": "taty4@gmail.com",
  "phoneNumber": 3489489237
}