####                                              ---------------- API ----------------

### Mostrar la informacion de la api
GET http://localhost:1904/api 

###                                         -------------------- USUARIOS ---------------------

### Mostrar todos los usuarios
GET http://localhost:1904/api/users

### Buscar por Id
GET http://localhost:1904/api/users/5f42e556-b69b-4945-895e-467d21fec7c0

### Registrar un usuario
POST http://localhost:1904/api/users/register
Content-Type: application/json

{
  "username": "Quimey Carro",
  "password": "290722",
  "email": "Quimey6@gmail.com",
  "phoneNumber": 3489520108
}

### Logearse
POST http://localhost:1904/api/users/login
Content-Type: application/json

{
  "username": "QuImEy cArRo",
  "password": "290722"
}

### Actualizar usuarios
PATCH http://localhost:1904/api/users/Pepito Lopez
Content-Type: application/json

{
  "email": "pepinito10@gmail.com",
  "phoneNumber": 9876543210
}

### Desloguearse
DELETE http://localhost:1904/api/users/logout
Content-Type: application/json

{
  "username": "Pepito Lopez"
}


### Borrar usuario de la base de datos
DELETE http://localhost:1904/api/users/Pepito Lopez

###                                                      ---------- Funciones de la api de Trapecio -----------

### Mostrar todas las figuras
GET http://localhost:1904/api/trapeze

### Mostrar la history general del trapecio
GET http://localhost:1904/api/trapeze/history

### Buscar por las figuras por Id
GET http://localhost:1904/api/trapeze/1

### Buscar imagenes por Id
GET http://localhost:1904/api/trapeze/image/1

### Buscar la guia para realizar una figura
GET http://localhost:1904/api/trapeze/steps/Candelabro invertido
Authorization:pasar token

### Crear figuras
POST http://localhost:1904/api/trapeze/create
Content-Type: application/json

{
  "name": "Split",
  "description": "The Split figure consists of opening your legs in opposite directions while you are suspended in the air with the help of the trapeze. The trapeze artist performs a series of movements to gain momentum and height before releasing from the trapeze and extending the legs to the sides in a split position. The position is held for a set amount of time, demonstrating control and flexibility, before grabbing the trapeze again to safely complete the figure.",
  "steps": [
    "The aerialist swings back and forth to gain momentum and height.",
    "At the right moment, the trapeze artist releases the trapeze and launches himself into the air.",
    "While in the air, the trapeze artist extends his legs to the sides in a split position",
    "The split position is held for a few seconds, showing control and flexibility.",
    "Finally, the trapeze artist grabs the trapeze with his hands again to safely complete the figure."
  ],
  "difficulty": "High",
  "images": {
    "jpg": {
      "image_url": "https://i.ytimg.com/vi/KlxqkXq-OU4/maxresdefault.jpg"
    }
  }
}

### Actualizar la informacion de una figura
PATCH http://localhost:1904/api/trapeze/2
Content-Type: application/json

{
  "name": "Doble",
  "difficulty": "ne"
}

### Eliminar una figura por Id
DELETE http://localhost:1904/api/trapeze/b6fff6c2-fe34-4080-968a-34e46764644f