###                                       --------------- API GENERAL INFORMATION --------------- 

### Mostrar la informacion de la api
GET http://localhost:1904/api 

###                                               --------------- USERS ---------------

### Mostrar todos los usuarios
GET http://localhost:1904/api/users
Authorization: c5eafaff-ed78-43f0-9fb8-d6e991d7db7f

### Buscar por Id
GET http://localhost:1904/api/users/98350e5e-3581-427b-9b05-ad006e990752
Authorization: c5eafaff-ed78-43f0-9fb8-d6e991d7db7f

### Registrar un usuario
POST http://localhost:1904/api/users/register
Content-Type: application/json

{
  "username": "Carolina Sordini",
  "password": "12345",
  "email": "carito4@gmail.com",
  "phoneNumber": 3489334895
}

### Logearse
POST http://localhost:1904/api/users/login
Content-Type: application/json

{
  "username": "Tatiana Aylen Vega",
  "password": "29072022"
}

### Actualizar usuarios
PATCH http://localhost:1904/api/users/carolina SORDIni
Authorization: c5eafaff-ed78-43f0-9fb8-d6e991d7db7f
Content-Type: application/json

{
  "email": "pepinito10@gmail.com",
  "phoneNumber": 9876543210
}

### Desloguearse
DELETE http://localhost:1904/api/users/logout
Authorization: c5eafaff-ed78-43f0-9fb8-d6e991d7db7f
Content-Type: application/json

{
  "username": "Tatiana Aylen Vega"
}


### Borrar usuario de la base de datos
DELETE http://localhost:1904/api/users/carolina SORDIni
Authorization: c5eafaff-ed78-43f0-9fb8-d6e991d7db7f

###                                       --------------- TRAPEZOID API FUNCTIONS ------------

### Mostrar todas las figuras
GET http://localhost:1904/api/trapeze
Authorization: c5eafaff-ed78-43f0-9fb8-d6e991d7db7f

### Mostrar las figuras por su dificultad (queryparams)
GET http://localhost:1904/api/trapeze?difficulty=high
Authorization: c5eafaff-ed78-43f0-9fb8-d6e991d7db7f

### Mostrar la historia general del trapecio
GET http://localhost:1904/api/trapeze/history
Authorization: c5eafaff-ed78-43f0-9fb8-d6e991d7db7f

### Buscar las figuras por id
GET http://localhost:1904/api/trapeze/605e9b99-b341-4cf9-bbb5-39a1e7b8b362
Authorization: c5eafaff-ed78-43f0-9fb8-d6e991d7db7f

### Buscar imagenes por id
GET http://localhost:1904/api/trapeze/image/605e9b99-b341-4cf9-bbb5-39a1e7b8b362
Authorization: c5eafaff-ed78-43f0-9fb8-d6e991d7db7f

### Buscar la guia para realizar una figura
GET http://localhost:1904/api/trapeze/steps/Squad
Authorization: c5eafaff-ed78-43f0-9fb8-d6e991d7db7f


### Crear figuras
POST http://localhost:1904/api/trapeze/create
Authorization: c5eafaff-ed78-43f0-9fb8-d6e991d7db7f
Content-Type: application/json

{
  "name": "Split",
  "description": "The Split figure consists of opening your legs in opposite directions while you are suspended in the air with the help of the trapeze. The trapeze artist performs a series of movements to gain momentum and height before releasing from the trapeze and extending the legs to the sides in a split position. The position is held for a set amount of time, demonstrating control and flexibility, before grabbing the trapeze again to safely complete the figure.",
  "steps": [
    "The aerialist swings back and forth to gain momentum and height.",
    "At the right moment, the trapeze artist releases the trapeze and launches himself into the air.",
    "While in the air, the trapeze artist extends his legs to the sides in a split position",
    "The split position is held for a few seconds, showing control and flexibility.",
    "Finally, the trapeze artist grabs the trapeze with his hands again to safely complete the figure."
  ],
  "difficulty": "High",
  "images": "https://i.ytimg.com/vi/KlxqkXq-OU4/maxresdefault.jpg"
}

### Actualizar la informacion de una figura
PATCH http://localhost:1904/api/trapeze/605e9b99-b341-4cf9-bbb5-39a1e7b8b362
Authorization: c5eafaff-ed78-43f0-9fb8-d6e991d7db7f
Content-Type: application/json

{
  "name": "Split",
  "difficulty": "High"
}

### Eliminar una figura por id
DELETE http://localhost:1904/api/trapeze/605e9b99-b341-4cf9-bbb5-39a1e7b8b362
Authorization: c5eafaff-ed78-43f0-9fb8-d6e991d7db7f